    -> ADD PRIMARY KEY (ID);


mysql> ALTER TABLE STUDENT
    -> ADD CONSTRAINT STU_NAME UNIQUE (NAME);


mysql> ALTER TABLE STUDENT
    -> MODIFY AGE INT DEFAULT 18;


mysql> ALTER TABLE STUDENT
    -> MODIFY DEPT VARCHAR(20) NOT NULL;


mysql> ALTER TABLE STUDENT
    -> ADD DEPT_NAME VARCHAR(20);


mysql> ALTER TABLE STUDENT
    -> ADD CONSTRAINT DEPT_IDS FOREIGN KEY (DEPT_NAME) REFERENCES DEPT(DEPT_NAME);
