USE VAZID;
CREATE TABLE EMP_DETAILS (NAME VARCHAR(20),AGE INT, CITY VARCHAR(40),STATE VARCHAR(50));

INSERT INTO EMP_DETAILS VALUES ("RAJU",25,"NELLORE","AP"),
								("RAMU",23,"GUNTUR","AP"),
                                ("VASU",25,"HYDERABAD","TG"),
                                ("MUZUU",21,"BANGLORE","KA"),
                                ("VAZID",23,"HYDERABAD","TG"),
                                ("RAJESH",23,"HYDERABAD","TG"),
                                ("SAMPATH",21,"BANGLORE","KA"),
                                ("NITEESH",23,"HYDERABAD","TG");

-- DDL COMMANDS
-- CREATE, ALTER, DROP , RENAME ,TRUNCATE -> ACTUALLY TO MODIFY THE TABLE STRUCTUTRE 

ALTER TABLE EMP_DETAILS  -- > ADDING NEW COLUMN 
ADD LAST_NAME VARCHAR(20);

ALTER TABLE EMP_DETAILS
MODIFY NAME VARCHAR(30);

ALTER TABLE EMP_DETAILS
RENAME column NAME TO FULL_NAME;

ALTER TABLE EMP_DETAILS
DROP column LAST_NAME;

SELECT* FROM EMP_DETAILS;

-- DML COMMANDS -> USED TO CHANGE THE DATA INSIDE THE TABLE
-- INSERT, UPDATE, DELETE

CREATE TABLE CUS_DET(ID INT ,NAME VARCHAR(10),AGE INT ,PHONE_NUMBER BIGINT(10));

-- INSERT
INSERT INTO CUS_DET (ID,NAME,AGE,PHONE_NUMBER) 
VALUES		(121,"VAZID",23,9390715405),
			(123,"RAJESH",21,8074405334),
            (125,"NITEESH",22,956743413),
            (145,"SAMPATH",21,8523056873);
            
-- UPDATE 
SET SQL_SAFE_UPDATES = 0;

UPDATE CUS_DET
SET AGE = 21
WHERE AGE = 23;

DELETE FROM CUS_DET
WHERE ID = 145;

SELECT * FROM CUS_DET;

-- DELETE
DELETE FROM CUST_DET
WHERE ID = 125;

SELECT * FROM CUST_DET;









            


            
