CREATE DATABASE COMPANY;
USE COMPANY;

CREATE TABLE employees (
    emp_id INT PRIMARY KEY,
    emp_name VARCHAR(50),
    department VARCHAR(50),
    salary INT,
    age INT,
    city VARCHAR(50),
    gender CHAR(1)
);

INSERT INTO employees (emp_id, emp_name, department, salary, age, city, gender) VALUES
(1, 'Rahul', 'IT', 55000, 28, 'Mumbai', 'M'),
(2, 'Priya', 'Human Resources', 33000, 26, 'Delhi', 'F'),
(3, 'Vikram', 'Sales', 38000, 32, 'Chennai', 'M'),
(4, 'Sneha', 'IT', 60000, 30, 'Bangalore', 'F'),
(6, 'Asha', 'Human Resources', 45000, 29, 'Delhi', 'F'),
(7, 'Manoj', 'IT', 50000, 27, 'Mumbai', 'M'),
(8, 'Deepak', 'Support', 33000, 31, 'Pune', 'M'),
(9, 'Neha', 'Sales', 41000, 26, 'Chennai', 'F'),
(11, 'Arjun', 'IT', 72000, 40, 'Bangalore', 'M'),
(12, 'Divya', 'Support', 35000, 25, 'Pune', 'F'),
(13, 'Jatin', 'Human Resources', 47000, 28, 'Mumbai', 'M'),
(14, 'Rohit', 'Sales', 39000, 24, 'Delhi', 'M'),
(15, 'Meera', 'Finance', 80000, 30, 'Chennai', 'F'),
(16, 'Rahul', 'IT', 50000, 30, NULL, 'M');

-- USING GROUP BY IN THE QUERY 
SELECT DEPARTMENT,COUNT(*) AS EMPLOYEES_COUNT FROM EMPLOYEES 
GROUP BY DEPARTMENT;

SELECT CITY,SUM(SALARY) AS TOTAL_SALARY FROM EMPLOYEES
WHERE CITY IS NOT NULL 
GROUP BY CITY
ORDER BY TOTAL_SALARY ;

-- UPDATING SEPFIC EMPS
UPDATE EMPLOYEES
SET GENDER = 'M'
WHERE EMP_ID IN (1,3,7,8,11,13,14,16);

-- UPDATING BY ALSO USING ORDER BY
 SELECT CITY,COUNT(*) AS TOTAL_EMPS FROM EMPLOYEES GROUP BY CITY ORDER BY TOTAL_EMPS DESC;

SELECT * FROM EMPLOYEES;


-- GROUP BY
SELECT DEPARTMENT,SUM(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT;

-- NUM OF EMPS IN EACH DEPT
SELECT DEPARTMENT,COUNT(SALARY) AS TOTAL_EMPS FROM EMPLOYEES GROUP BY DEPARTMENT;

-- AVG SALARY OF EACH DEPT
SELECT DEPARTMENT,TRUNCATE(AVG(SALARY),3) AS AVG_SALARY FROM EMPLOYEES GROUP BY DEPARTMENT;

-- MAX AND MIN SALARY IN THE EACH DEPT 
SELECT DEPARTMENT, MAX(SALARY) AS MAX_SALARY ,MIN(SALARY) AS MIN_SALARY FROM EMPLOYEES  GROUP BY DEPARTMENT;

--  SELECT PEOPLE IN EACH CITY
SELECT CITY,COUNT(EMP_NAME) FROM EMPLOYEES
WHERE CITY IS NOT NULL AND CITY !="DELHI"
GROUP BY CITY
HAVING COUNT(*)>=3; 

-- MAX MIN AVG SUM
SELECT CITY,SUM(SALARY),TRUNCATE(AVG(SALARY),2) AS AVG_SAL,MIN(SALARY),MAX(SALARY) FROM EMPLOYEES 
WHERE CITY IS NOT NULL
GROUP BY CITY;

-- by age group
SELECT AGE, COUNT(EMP_NAME) AS TOTAL_EMPS FROM EMPLOYEES  GROUP BY AGE ORDER BY AGE; 

-- TWO GROUPS DEPT,CITY COUNT COUNT EMP 
SELECT DEPARTMENT,CITY,COUNT(EMP_NAME) FROM EMPLOYEES GROUP BY DEPARTMENT,CITY;

-- GROUP BY DEPT SALARY > 50000
SELECT DEPARTMENT,COUNT(*) FROM EMPLOYEES WHERE SALARY>50000 GROUP BY DEPARTMENT;

--  FIND SAL EMP SAL > 40K GRUP BY CITY
SELECT CITY,COUNT(*) FROM EMPLOYEES WHERE CITY IS NOT NULL AND SALARY >40000 GROUP BY CITY;
 
 -- M AND F
 SELECT GENDER,COUNT(*) FROM EMPLOYEES GROUP BY GENDER;
 
-- AVG AGE OF EACH DEPT
SELECT DEPARTMENT,AVG(AGE) FROM EMPLOYEES GROUP BY DEPARTMENT;

-- GROUP BY GENDER
SELECT GENDER,COUNT(*) FROM EMPLOYEES GROUP BY GENDER;

